#!/usr/bin/env bash
# Install HAproxy

sudo apt-get update
sudo apt-get install -y haproxy

#Install Certbot
sudo apt-get install -y certbot

suco certbot certonly --standalone -d www.yourdomain.com

#Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.yourdomain.com/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    balance roundrobin
    server web-server-1 your_web_server_1_ip:your_web_server_1_port check
    server web-server-2 your_web_server_2_ip:your_web_server_2_port check
EOF

sudo service haproxy restart
