#!/usr/bin/env bash
# Install HAproxy

sudo apt-get update
sudo apt-get install -y haproxy

#Install Certbot
sudo apt-get install -y certbot

sudo certbot certonly --standalone -d www.yourdomain.com

#Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.yourdomain.com/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    balance roundrobin
    server web-server-1 192.168.1.1:80 check
    server web-server-2 192.168.1.2:80 check

EOF

sudo service haproxy restart
