#!/usr/bin/env bash
# Install and configure Nginx web server on Ubuntu

apt-get update -y
apt-get install -y nginx

#Create simple HTML page
echo "Hello World!" > /var/www/html/index.html

#Make sure Nginx is listening on port 80
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    erver_name 375416-web-01;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

#Restart Nginx
service nginx restart
