#!/usr/bin/env bash
# Install and configure Nginx web server on Ubuntu

apt-get update -y
apt-get install -y nginx

#Create simple HTML page
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

#Make sure Nginx is listening on port 80
print %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default

#Restart Nginx
service nginx restart
