#!/usr/bin/env bash
# Configure Nginx server to listen on port 80
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
