#!/usr/bin/env bash
# This script displays hours from 0 tp 12 and minutes from 1 to 59

hour=0
while [ $hour -le 12 ]; do
	echo "Hour: $hour"

	if [ $hour -eq 0 ]; then
		minute=1
	else
		minute=0
	fi

	while [ $minute -lt 60 ]; do
		echo $minute
		minute=$((minute+1))
	done

	hour=$((hour+1))
done
