#!/usr/bin/env bash
# This script displays all active IPv4 addresses on machine

ipv4_addresses=$(ip -4 addr show | grep -oE 'inet ([0-9]{1,3}\.){3}[0-9]{1,3}' | awk '{print $2}')

for address in $ipv4_addresses; do
  echo "$address"
done
