#!/usr/bin/env bash
# This script configures container to run Nginx as nginx user

sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

service nginx restart

ps auxff | grep "nginx"

nc -z 0 8080
