#!/usr/bin/env bash
# This script configures container to run Nginx as nginx user

#sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

#service nginx restart

#ps auxff | grep "nginx"

#nc -z 0 8080
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
sudo -u nginx service nginx restart
