#!/usr/bin/env bash
server {
  listen 80 default_server;
  listen[::]:80 default_server;
  server_name 100.26.10.206
  add_header X-Served-By 375416-web-01;

  # Serves /airbnb-onepage/ route on AirBnb_clone_v3
  location = /airbnb_onepage/ {
    proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
  }

  error_page 404 /404.html;
  location /404 {
    root /var/www/html;
    internal;
  }
}
